export const AUDIO_CONFIG = {
  LOUDNESS_THRESHOLD_DECIBELS: -38,
  MINIMUM_SILENCE_DURATION_MS: 800,

  METERING_POLL_INTERVAL: 100,
  MAX_RECORDING_DURATION_MS: 30_000,

  PITCH_RATE: 5.5, 
  VOLUME: 1,
} as const;